In [9]:
# Marc Garcia
# libriaries
import pandas as pd
import numpy as np

df = pd.read_csv('Station_list.csv')

# create an empty dictionary to store the data
data = {}

# iterate over each row in the DataFrame
for _, row in df.iterrows():

    # create a dictionary for each station
    station_data = {
        "latitude": row["lat"],
        "longitude": row["lon"],
        "elevation(m)": row["elv(m)"],
        "unit": row["unit"],
        "component": row["componet"].split(","),
        "response": [float(x) for x in row["response"].split(",")]
    }

    # add the station data to the main dictionary
    data[row["station"]] = station_data

# write the data to a JSON file
with open('Station_list.json', 'w') as f:
    json.dump(data, f, indent=2)

NameError: name 'json' is not defined

,station,lat,lon,elv(m),unit,componet,response
0,4B.101..GP,31.78592,-106.22352,1226,m/s,"1,2,Z","1507118400.00000, 1507118400.00000, 1507118400..."
1,4B.102..GP,31.70360,-106.33703,1118,m/s,"1,2,Z","1507118400.00000, 1507118400.00000, 1507118400..."
2,4B.103..GP,31.85575,-106.52372,1345,m/s,"1,2,Z","1507118400.00000, 1507118400.00000, 1507118400..."
3,4B.104..GP,31.79870,-106.54338,1159,m/s,"1,2,Z","1507118400.00000, 1507118400.00000, 1507118400..."
4,4B.105..GP,31.62117,-106.27982,1113,m/s,"1,2,Z","1507118400.00000, 1507118400.00000, 1507118400..."